version: '3'
services:
    mongo:
        container_name: mongo1 # 跟本机已有镜像重名
        image: mongo
        ports:
            - '27017:27017'
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example123
            MONGO_INITDB_DATABASE: front
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example123
    nginx:
        build:
            context: ./webapp
        ports:
            # - "80:80"
            - "443:443"
            - "3000:3000"
            - "3002:3002"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/cert:/etc/nginx/cert
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            #networks:
            #- backend
        restart: always
    server:
        build:
            context: ./server
        ports:
            - "3100:3100"
            # restart: always
            #depends_on:
            #    - mongo
            #networks:
            #- backend
